levels/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.conf.urls import include, url

from .views import *

urlpatterns = [
    url(r'^$', level_list, name="level_list"),
    url(r'^add/$', add_level, name="add_level"),
    url(r'^(?P<slug>[^/]+)/$', level_detail, name="level_detail"),
    url(r'^(?P<slug>[^/]+)/project.json$', level_project_json, name="level_project_json"),
    url(r'^(?P<slug>[^/]+)/change/$', change_level, name="change_level"),
]

social_labyrinth/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.shortcuts import render, redirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    #url(r'^$', lambda request: render(request, template_name="index.html"), name="index"),
    url(r'^$', lambda request: redirect('level_list')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name="user_logout"),
    url(r'^levels/', include('levels.urls')),
    url('', include('django.contrib.auth.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
]

urlpatterns += staticfiles_urlpatterns()

levels/models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.html import mark_safe


class Level(models.Model):
    created = models.DateTimeField(_("created"), auto_now_add=True)
    modified = models.DateTimeField(_("modified"), auto_now=True)
    author = models.ForeignKey("auth.User", verbose_name=_("author"))
    title = models.CharField(_("title"), max_length=255)
    slug = models.SlugField(_("slug"), max_length=255)
    labyrinth = models.TextField(_("labyrinth"), help_text=_('"#" - bricks, " " - spaces, "*" - collectables, "p" - player, "e" - exit'))

    class Meta:
        verbose_name = _("Level")
        verbose_name_plural = _("Levels")

    def __str__(self):
        return self.title

    def render_labyrinth(self):
        html = []
        html.append('<table>')
        for line in self.labyrinth.splitlines():
            html.append('<tr>')
            for char in line:
                html.append('<td>')
                if char == " ":
                    html.append('<img src="/static/site/img/space.png" />')
                if char == "#":
                    html.append('<img src="/static/site/img/brick.png" />')
                if char == "*":
                    html.append('<img src="/static/site/img/collectable.png" />')
                if char == "p":
                    html.append('<img src="/static/site/img/player.png" />')
                if char == "e":
                    html.append('<img src="/static/site/img/exit.png" />')
                html.append('</td>')
            html.append('</tr>')
        html.append('</table>')
        return mark_safe(''.join(html))

    def render_labyrinth_json(self):
        import json
        rows = []
        for line in self.labyrinth.splitlines():
            row = []
            for char in line:
                row.append(char)
            rows.append(row)
        return mark_safe(json.dumps(rows))

levels/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden

from crispy_forms.helper import FormHelper
from crispy_forms import layout, bootstrap

from .models import Level


class LevelForm(forms.ModelForm):
    class Meta:
        model = Level
        fields = ['title', 'labyrinth']

    def __init__(self, request, *args, **kwargs):
        super(LevelForm, self).__init__(*args, **kwargs)
        self.request = request

        self.helper = FormHelper()
        self.helper.form_action = ""
        self.helper.form_method = "POST"

        self.helper.layout = layout.Layout(
            "title",
            "labyrinth",
            bootstrap.FormActions(
                layout.Submit('submit', _('Save')),
            )
        )

    def save(self, commit=True):
        level = super(LevelForm, self).save(commit=False)
        level.author = self.request.user
        level.slug = slugify(self.cleaned_data['title'])
        if commit:
            level.save()
        return level


def level_list(request):
    levels = Level.objects.all()
    return render(request, 'levels/level_list.html', {'levels': levels})


def level_detail(request, slug):
    level = get_object_or_404(Level, slug=slug)
    return render(request, 'levels/level_detail.html', {'level': level})


def level_project_json(request, slug):
    level = get_object_or_404(Level, slug=slug)
    return render(request, 'levels/level_project_json.json', {'level': level})


@login_required
def add_level(request):
    if request.method == "POST":
        form = LevelForm(request, data=request.POST)
        if form.is_valid():
            level = form.save()
            return redirect('level_detail', slug=level.slug)
    else:
        form = LevelForm(request)
    return render(request, 'levels/change_level.html', {'form': form})


@login_required
def change_level(request, slug):
    level = get_object_or_404(Level, slug=slug)
    if level.author != request.user:
        return HttpResponseForbidden('You do not have permissions to edit this level.')
    if request.method == "POST":
        form = LevelForm(request, data=request.POST, instance=level)
        if form.is_valid():
            level = form.save()
            return redirect('level_detail', slug=level.slug)
    else:
        form = LevelForm(request, instance=level)
    return render(request, 'levels/change_level.html', {'form': form})

social_labyrinth/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Social Labyrinths</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
        <style>
            #id_labyrinth {
                font-family: monospace;
            }

        </style>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body role="document">
        <!-- Fixed navbar -->
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Social Labyrinths</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url "level_list" %}">Levels</a></li>
                        {% if not request.user.is_authenticated %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/login/yahoo/?next={{ request.path }}">Yahoo!</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user.username }} <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url "user_logout" %}?next={{ request.path }}">Logout</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container theme-showcase" role="main">

            <!-- Main jumbotron for a primary marketing message or call to action -->
            <div class="jumbotron">
                <h1>Social Labyrinths</h1>
                <p>Walk through labyrinths. Create labyrinths.</p>
            </div>

            {% block content %}

            {% endblock %}
        </div>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        {% block extrabody %}{% endblock %}
    </body>
</html>

social_labyrinth/templates/index.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

social_labyrinth/templates/levels/change_level.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {{ form.non_field_errors }}
    {{ form.errors }}
    {% crispy form %}
{% endblock %}

social_labyrinth/templates/levels/level_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ level.title }}
        {% if request.user == level.author %}
            <a href="{% url "change_level" slug=level.slug %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
    </h1>
    {% comment %}
    {{ level.render_labyrinth }}
    {% endcomment %}
    <script>
        var labyrinth = JSON.parse('{{ level.render_labyrinth_json }}');
    </script>

    <canvas id="gameCanvas"></canvas>
{% endblock %}

{% block extrabody %}
    <script src="{{ STATIC_URL }}site/js/cocos2d-js-v3.6-min.js" charset="UTF-8"></script>
    <script>
        var STATIC_URL = '{{ STATIC_URL }}';
        var KEY_LEFT_CODE = 37;
        var KEY_RIGHT_CODE = 39;
        var KEY_UP_CODE = 38;
        var KEY_DOWN_CODE = 40;
        var TILE_SIZE = 35;
        var level_title = '{{ level.title }}';
        var sprites = {
            '#': STATIC_URL + 'site/img/brick.png',
            '*': STATIC_URL + 'site/img/collectable.png',
            'e': STATIC_URL + 'site/img/exit.png',
            'p': STATIC_URL + 'site/img/player.png'
        };
        var player_position;
        var player_sprite;
        var collectables_positions = [];
        var collectables_sprites = [];
    </script>
    <script src="{{ STATIC_URL }}site/js/main.js"></script>
{% endblock %}

social_labyrinth/templates/levels/level_list.html
{% extends "base.html" %}

{% block content %}
    <ul>
    {% for level in levels %}
        <li><a href="{% url "level_detail" slug=level.slug %}">{{ level.title }}</a> by {{ level.author.username }}</li>
    {% endfor %}
    </ul>
    {% if request.user.is_authenticated %}
        <p><a href="{% url "add_level" %}">Create labyrinth</a></p>
    {% endif %}
{% endblock %}